version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  labels:
  - "dependencies"
  commit-message:
    prefix: "deps:"
  versioning-strategy: "increase-if-necessary"
  # Disable version updates unless they are for security reasons.
  open-pull-requests-limit: 0